# Сила приоритета (рекомендуется от 1.0 до 5.0)
# 1.0 — Линейное распределение (если вещь сломана в 2 раза сильнее, она получит в 2 раза больше опыта).
# 2.0 — Квадратичное (самые сломанные вещи будут забирать почти весь опыт, пока не сравняются с остальными).
# Чем выше число, тем жестче фокус на самые "убитые" вещи.
priority-power: 2.5