# Настройка силы приоритета (от 1.0 до 10.0)
# 1.0 - Линейное распределение (просто делит опыт между всеми вещами)
# 2.5 - Оптимально (сильно сломанные вещи забирают больше опыта)
# 5.0 - Жестко (почти весь опыт идет на самую сломанную вещь)
priority-power: 2.5

messages:
  # Поддержка обычных кодов (&f) и HEX (&#RRGGBB)
  reload-success: "&#55FF55[BloodFix] &#FFFFFFКонфигурация успешно перезагружена!"
  no-permission: "&#FF5555[BloodFix] &#FFFFFFУ вас нет прав для выполнения этой команды."